### ISSUE TITLE
Контроль баланса при заказах

### ISSUE THREAD

**Issue by Yurik72** [Ferolka/catering#18]
Необходимо добавить новое поле прогнозируемый баланс  "TotalPreOrderBalance" в финансовые данные пользователя. Смотри аналогию "TotalPreOrderedAmount"  
Соответственно при каждом заказе со статусом Confirmed, необходимо его пересчитывать.
Не забыть также его пересчитать в момент реальной оплаты, т.к. он уйдет в другую графу -> реального баланса
И теперь для чего все это: При попытке заказать что нибудь следующее , сделать запрет если уже пользователь уходит в минус. Т.е. согласно  требований клиента пользователь может уйти в минус только на 1 заказ
Например TotalPreOrderBalance= 30
Пользователь заказал на сумму 80. PreOrderBalance =30-80=(-50) Это еще можно, 
Но дальше , как только баланс отрицательный, пользователь уже ничего не сможет заказать :(
"TotalPreOrderBalance"  -> алгоритм расчета , это всегда актуальное число, Текущий Баланс "Balance"  минус (-) "сумма" заказов со статусом IsConfrimed=true and IsPaid=false

**Comment by Ferolka** [comment]
При заказе он автоматом потвержден, проверку на IsConfrimed не где вставлять (пока), Нужна помощь в моменте где заказ IsPaid становиться для апдейта TotalPreOrderedAmount
