### ISSUE TITLE
Реализация процесса заказа

### ISSUE THREAD

**Issue by Yurik72** [Ferolka/catering#5]
Согласно требованиям
[Замовлення.docx](https://github.com/Ferolka/catering/files/4911732/default.docx)

Уточнения,
1. В компании добавить новый аттрибут OrderType  (bit flag)

0 : Ничего нельзя
1 : Можно Комплексы
2 : Можно Блюда
4 : Можно только один комплекс

Соответственно поменять реализацию логики заказа для случая 4 (Один комплекс)

Если в корзине уже есть заказанный комплекс, то новый добавить уже нельзя, можно только очистить корзину
и после этого можно опять добавлять комплексы

**Comment by Ferolka** [comment]
if( ! Checked by admin) не можна замовляти
